export type EmojiEntry = {
  emoji: string;
  keywords: string[];
};

export type EmojiCategory = {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
};

function e(emoji: string, keywords: string[]): EmojiEntry {
  return { emoji, keywords };
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😀",
    emojis: [
      e("😀", ["grin", "happy", "smile"]),
      e("😃", ["smiley", "joy"]),
      e("😄", ["laugh", "happy"]),
      e("😁", ["beaming", "grin"]),
      e("😆", ["laughing", "squint"]),
      e("😅", ["sweat", "relief"]),
      e("🤣", ["rofl", "lol"]),
      e("😂", ["joy", "tears", "lol"]),
      e("🙂", ["slight", "smile"]),
      e("🙃", ["upside", "sarcasm"]),
      e("😉", ["wink"]),
      e("😊", ["blush", "warm"]),
      e("😇", ["angel", "innocent"]),
      e("🥰", ["love", "hearts"]),
      e("😍", ["heart eyes", "love"]),
      e("🤩", ["star", "excited"]),
      e("😘", ["kiss"]),
      e("😗", ["kissing"]),
      e("😚", ["kiss closed"]),
      e("😙", ["kiss smile"]),
      e("🥲", ["tear", "smile"]),
      e("😋", ["yum", "tongue"]),
      e("😛", ["tongue"]),
      e("😜", ["wink tongue", "crazy"]),
      e("🤪", ["zany", "wild"]),
      e("😝", ["tongue closed"]),
      e("🤑", ["money", "rich"]),
      e("🤗", ["hug"]),
      e("🤭", ["giggle", "oops"]),
      e("🤫", ["shush", "quiet"]),
      e("🤔", ["think", "hmm"]),
      e("🫡", ["salute"]),
      e("🤐", ["zipper", "secret"]),
      e("🤨", ["raised eyebrow", "skeptical"]),
      e("😐", ["neutral"]),
      e("😑", ["expressionless"]),
      e("😶", ["no mouth", "speechless"]),
      e("🫥", ["dotted", "invisible"]),
      e("😏", ["smirk"]),
      e("😒", ["unamused"]),
      e("🙄", ["eye roll"]),
      e("😬", ["grimace"]),
      e("🤥", ["lying", "pinocchio"]),
      e("😌", ["relieved"]),
      e("😔", ["pensive", "sad"]),
      e("😪", ["sleepy"]),
      e("🤤", ["drool"]),
      e("😴", ["sleep", "zzz"]),
      e("🥱", ["yawn", "tired"]),
      e("😷", ["mask", "sick"]),
      e("🤒", ["thermometer", "sick"]),
      e("🤕", ["bandage", "hurt"]),
      e("🤢", ["nauseated"]),
      e("🤮", ["vomit"]),
      e("🤧", ["sneeze"]),
      e("🥵", ["hot"]),
      e("🥶", ["cold", "freeze"]),
      e("😵", ["dizzy"]),
      e("🤯", ["mind blown", "explode"]),
      e("🥳", ["party", "celebrate"]),
      e("🥸", ["disguise"]),
      e("😎", ["cool", "sunglasses"]),
      e("🤓", ["nerd", "glasses"]),
      e("🧐", ["monocle", "inspect"]),
    ],
  },
  {
    id: "gestures",
    label: "People",
    icon: "👋",
    emojis: [
      e("👋", ["wave", "hello", "hi"]),
      e("🤚", ["raised back hand"]),
      e("🖐️", ["hand", "five"]),
      e("✋", ["stop", "high five"]),
      e("🖖", ["vulcan", "spock"]),
      e("🫱", ["rightwards", "handshake"]),
      e("🫲", ["leftwards"]),
      e("🫳", ["palm down"]),
      e("🫴", ["palm up"]),
      e("👌", ["ok", "perfect"]),
      e("🤌", ["pinched", "italian"]),
      e("🤏", ["pinch", "small"]),
      e("✌️", ["peace", "victory"]),
      e("🤞", ["fingers crossed", "luck"]),
      e("🫰", ["heart hands"]),
      e("🤟", ["love you"]),
      e("🤘", ["rock", "horns"]),
      e("🤙", ["call me", "shaka"]),
      e("👈", ["point left"]),
      e("👉", ["point right", "look"]),
      e("👆", ["point up"]),
      e("👇", ["point down", "below"]),
      e("☝️", ["index up", "one"]),
      e("👍", ["thumbs up", "yes", "like"]),
      e("👎", ["thumbs down", "no"]),
      e("✊", ["fist", "power"]),
      e("👊", ["punch", "bump"]),
      e("🤛", ["fist left"]),
      e("🤜", ["fist right"]),
      e("👏", ["clap", "applause"]),
      e("🙌", ["raise hands", "celebrate"]),
      e("🫶", ["heart hands", "love"]),
      e("👐", ["open hands"]),
      e("🤲", ["palms up", "pray"]),
      e("🤝", ["handshake", "deal"]),
      e("🙏", ["pray", "thanks", "please"]),
      e("💪", ["muscle", "strong", "flex"]),
      e("🦾", ["mechanical arm"]),
      e("🧠", ["brain", "think", "smart"]),
      e("👀", ["eyes", "look", "watch"]),
      e("👁️", ["eye"]),
      e("💋", ["kiss", "lips"]),
      e("👶", ["baby"]),
      e("🧑", ["person"]),
      e("👨", ["man"]),
      e("👩", ["woman"]),
      e("🧑‍💻", ["technologist", "developer", "coder"]),
      e("👨‍💻", ["man technologist"]),
      e("👩‍💻", ["woman technologist"]),
      e("🧑‍💼", ["office worker", "professional"]),
      e("👨‍💼", ["businessman"]),
      e("👩‍💼", ["businesswoman"]),
      e("🧑‍🏫", ["teacher"]),
      e("🧑‍🎓", ["student", "graduate"]),
      e("🧑‍🔬", ["scientist"]),
      e("🧑‍🚀", ["astronaut"]),
      e("🧑‍🎨", ["artist"]),
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    icon: "❤️",
    emojis: [
      e("❤️", ["red heart", "love"]),
      e("🧡", ["orange heart"]),
      e("💛", ["yellow heart"]),
      e("💚", ["green heart"]),
      e("💙", ["blue heart"]),
      e("💜", ["purple heart"]),
      e("🖤", ["black heart"]),
      e("🤍", ["white heart"]),
      e("🤎", ["brown heart"]),
      e("💔", ["broken heart", "sad"]),
      e("❤️‍🔥", ["heart fire", "passion"]),
      e("❤️‍🩹", ["mending heart", "heal"]),
      e("💕", ["two hearts", "love"]),
      e("💞", ["revolving hearts"]),
      e("💓", ["beating heart"]),
      e("💗", ["growing heart"]),
      e("💖", ["sparkling heart"]),
      e("💘", ["cupid", "arrow"]),
      e("💝", ["gift heart"]),
      e("💟", ["heart decoration"]),
      e("♥️", ["heart suit"]),
      e("💌", ["love letter"]),
      e("😍", ["heart eyes"]),
      e("🥰", ["smiling hearts"]),
      e("😘", ["kiss"]),
      e("😻", ["heart eyes cat"]),
      e("💑", ["couple"]),
      e("👫", ["holding hands"]),
      e("🫶", ["heart hands"]),
    ],
  },
  {
    id: "work",
    label: "Work",
    icon: "💼",
    emojis: [
      e("💼", ["briefcase", "business", "job"]),
      e("📊", ["chart", "bar", "analytics", "data"]),
      e("📈", ["chart up", "growth", "trend"]),
      e("📉", ["chart down", "decline"]),
      e("📋", ["clipboard", "list", "tasks"]),
      e("📌", ["pin", "important"]),
      e("📍", ["location", "pin"]),
      e("📝", ["memo", "note", "write"]),
      e("✏️", ["pencil", "edit"]),
      e("🖊️", ["pen"]),
      e("📎", ["paperclip", "attach"]),
      e("🗂️", ["folder", "organize"]),
      e("📁", ["file folder"]),
      e("📂", ["open folder"]),
      e("🗃️", ["card file"]),
      e("📇", ["index", "contacts"]),
      e("📅", ["calendar", "date", "schedule"]),
      e("📆", ["tear off calendar"]),
      e("🗓️", ["spiral calendar"]),
      e("⏰", ["alarm", "time", "deadline"]),
      e("⏱️", ["stopwatch", "timer"]),
      e("⌛", ["hourglass", "wait"]),
      e("⏳", ["hourglass flowing"]),
      e("🎯", ["target", "goal", "focus"]),
      e("🏆", ["trophy", "win", "award"]),
      e("🥇", ["gold medal", "first"]),
      e("🥈", ["silver medal"]),
      e("🥉", ["bronze medal"]),
      e("🏅", ["medal"]),
      e("🎖️", ["military medal"]),
      e("📣", ["megaphone", "announce"]),
      e("📢", ["loudspeaker"]),
      e("🔔", ["bell", "notification"]),
      e("🔕", ["bell slash", "mute"]),
      e("💡", ["idea", "lightbulb", "insight"]),
      e("🔍", ["search", "magnify"]),
      e("🔎", ["magnifying right"]),
      e("🧩", ["puzzle", "piece", "problem"]),
      e("⚙️", ["gear", "settings", "process"]),
      e("🔧", ["wrench", "fix", "tool"]),
      e("🔨", ["hammer", "build"]),
      e("🛠️", ["tools", "fix"]),
      e("⚒️", ["hammer pick"]),
      e("🤝", ["handshake", "partnership", "deal"]),
      e("📧", ["email", "mail"]),
      e("📨", ["incoming mail"]),
      e("📩", ["envelope arrow"]),
      e("📮", ["postbox"]),
      e("🏢", ["office building", "company"]),
      e("🏭", ["factory"]),
      e("🏗️", ["construction", "build"]),
      e("🚀", ["rocket", "launch", "startup"]),
      e("📦", ["package", "ship", "delivery"]),
      e("✅", ["check", "done", "complete"]),
      e("☑️", ["check box"]),
      e("✔️", ["check mark"]),
      e("❌", ["cross", "no", "wrong"]),
      e("⭕", ["circle", "o"]),
      e("‼️", ["double exclamation"]),
      e("⁉️", ["exclamation question"]),
      e("❓", ["question"]),
      e("❗", ["exclamation", "important"]),
      e("💯", ["hundred", "perfect", "score"]),
    ],
  },
  {
    id: "tech",
    label: "Tech",
    icon: "💻",
    emojis: [
      e("💻", ["laptop", "computer", "code"]),
      e("🖥️", ["desktop", "monitor"]),
      e("⌨️", ["keyboard"]),
      e("🖱️", ["mouse"]),
      e("🖨️", ["printer"]),
      e("📱", ["phone", "mobile", "iphone"]),
      e("📲", ["phone arrow"]),
      e("☎️", ["telephone"]),
      e("📞", ["phone receiver", "call"]),
      e("📟", ["pager"]),
      e("📠", ["fax"]),
      e("🔋", ["battery"]),
      e("🔌", ["plug", "power"]),
      e("💾", ["floppy", "save"]),
      e("💿", ["cd", "disk"]),
      e("📀", ["dvd"]),
      e("🧮", ["abacus", "math"]),
      e("🎮", ["game", "controller"]),
      e("🕹️", ["joystick"]),
      e("📷", ["camera"]),
      e("📸", ["camera flash"]),
      e("📹", ["video camera"]),
      e("🎥", ["movie camera", "film"]),
      e("📺", ["tv", "television"]),
      e("📻", ["radio"]),
      e("🎙️", ["microphone", "podcast"]),
      e("🎧", ["headphones", "audio"]),
      e("🔊", ["speaker loud"]),
      e("🔉", ["speaker medium"]),
      e("🔈", ["speaker low"]),
      e("🔇", ["mute"]),
      e("📡", ["satellite", "antenna"]),
      e("🛰️", ["satellite orbit"]),
      e("🌐", ["globe", "internet", "web"]),
      e("🔗", ["link", "chain", "url"]),
      e("⛓️", ["chains"]),
      e("🔒", ["lock", "secure"]),
      e("🔓", ["unlock", "open"]),
      e("🔐", ["locked key"]),
      e("🔑", ["key", "password"]),
      e("🗝️", ["old key"]),
      e("🛡️", ["shield", "security"]),
      e("⚡", ["lightning", "fast", "power"]),
      e("🔥", ["fire", "hot", "trending"]),
      e("💾", ["save"]),
      e("🤖", ["robot", "ai", "bot"]),
      e("🧬", ["dna", "science"]),
      e("🔬", ["microscope", "science"]),
      e("🔭", ["telescope"]),
      e("📐", ["triangle ruler"]),
      e("📏", ["ruler"]),
      e("🧪", ["test tube", "experiment"]),
      e("⚗️", ["alembic"]),
      e("🧫", ["petri dish"]),
      e("💉", ["syringe"]),
      e("🩺", ["stethoscope"]),
      e("🏥", ["hospital"]),
    ],
  },
  {
    id: "celebrate",
    label: "Party",
    icon: "🎉",
    emojis: [
      e("🎉", ["party", "celebrate", "tada"]),
      e("🎊", ["confetti"]),
      e("🎈", ["balloon"]),
      e("🎁", ["gift", "present"]),
      e("🎀", ["ribbon"]),
      e("🎂", ["cake", "birthday"]),
      e("🍾", ["champagne", "celebrate"]),
      e("🥂", ["cheers", "toast"]),
      e("🍻", ["beers", "cheers"]),
      e("✨", ["sparkles", "magic", "new"]),
      e("🌟", ["glowing star"]),
      e("⭐", ["star"]),
      e("🌠", ["shooting star"]),
      e("💫", ["dizzy star"]),
      e("🔥", ["fire", "lit"]),
      e("🎆", ["fireworks"]),
      e("🎇", ["sparkler"]),
      e("🎵", ["music note"]),
      e("🎶", ["music notes"]),
      e("🎤", ["microphone", "sing"]),
      e("🎧", ["headphones"]),
      e("🎸", ["guitar", "rock"]),
      e("🎹", ["piano"]),
      e("🎺", ["trumpet"]),
      e("🎻", ["violin"]),
      e("🪩", ["disco ball"]),
      e("🥳", ["party face"]),
      e("🏆", ["trophy"]),
      e("🥂", ["clink"]),
      e("👏", ["clap"]),
      e("🙌", ["raise hands"]),
      e("💃", ["dance woman"]),
      e("🕺", ["dance man"]),
      e("🪅", ["pinata"]),
      e("🎭", ["theater", "drama"]),
      e("🎪", ["circus"]),
      e("🎟️", ["tickets"]),
      e("🎫", ["ticket"]),
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🌱",
    emojis: [
      e("🌱", ["seedling", "grow", "startup"]),
      e("🌿", ["herb", "leaf"]),
      e("🍀", ["clover", "luck"]),
      e("🌳", ["tree"]),
      e("🌲", ["evergreen"]),
      e("🌴", ["palm", "vacation"]),
      e("🌵", ["cactus"]),
      e("🌷", ["tulip"]),
      e("🌸", ["cherry blossom", "spring"]),
      e("💐", ["bouquet", "flowers"]),
      e("🌹", ["rose", "love"]),
      e("🌺", ["hibiscus"]),
      e("🌻", ["sunflower"]),
      e("🌼", ["blossom"]),
      e("🌍", ["earth", "africa", "globe"]),
      e("🌎", ["americas"]),
      e("🌏", ["asia"]),
      e("🌕", ["full moon"]),
      e("🌙", ["crescent moon", "night"]),
      e("⭐", ["star"]),
      e("🌞", ["sun"]),
      e("☀️", ["sunny"]),
      e("🌤️", ["sun cloud"]),
      e("⛅", ["partly cloudy"]),
      e("🌥️", ["cloud sun"]),
      e("☁️", ["cloud"]),
      e("🌧️", ["rain"]),
      e("⛈️", ["storm"]),
      e("🌈", ["rainbow", "diversity"]),
      e("❄️", ["snow", "cold"]),
      e("☃️", ["snowman"]),
      e("⛄", ["snowman no snow"]),
      e("🌊", ["wave", "ocean"]),
      e("🔥", ["fire"]),
      e("💧", ["droplet", "water"]),
      e("🌪️", ["tornado"]),
      e("🌋", ["volcano"]),
      e("🏔️", ["mountain snow"]),
      e("⛰️", ["mountain"]),
      e("🏕️", ["camping"]),
      e("🏖️", ["beach"]),
    ],
  },
  {
    id: "animals",
    label: "Animals",
    icon: "🐶",
    emojis: [
      e("🐶", ["dog", "puppy"]),
      e("🐱", ["cat", "kitten"]),
      e("🐭", ["mouse"]),
      e("🐹", ["hamster"]),
      e("🐰", ["rabbit", "bunny"]),
      e("🦊", ["fox"]),
      e("🐻", ["bear"]),
      e("🐼", ["panda"]),
      e("🐨", ["koala"]),
      e("🐯", ["tiger"]),
      e("🦁", ["lion"]),
      e("🐮", ["cow"]),
      e("🐷", ["pig"]),
      e("🐸", ["frog"]),
      e("🐵", ["monkey"]),
      e("🙈", ["see no evil"]),
      e("🙉", ["hear no evil"]),
      e("🙊", ["speak no evil"]),
      e("🐔", ["chicken"]),
      e("🐧", ["penguin"]),
      e("🐦", ["bird"]),
      e("🦅", ["eagle"]),
      e("🦆", ["duck"]),
      e("🦉", ["owl", "wise"]),
      e("🐴", ["horse"]),
      e("🦄", ["unicorn", "magic", "startup"]),
      e("🐝", ["bee", "busy"]),
      e("🦋", ["butterfly"]),
      e("🐌", ["snail", "slow"]),
      e("🐢", ["turtle", "slow"]),
      e("🐍", ["snake"]),
      e("🦎", ["lizard"]),
      e("🐙", ["octopus"]),
      e("🦑", ["squid"]),
      e("🦐", ["shrimp"]),
      e("🐠", ["fish tropical"]),
      e("🐟", ["fish"]),
      e("🐬", ["dolphin"]),
      e("🐳", ["whale"]),
      e("🦈", ["shark"]),
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "☕",
    emojis: [
      e("☕", ["coffee", "cafe", "morning"]),
      e("🍵", ["tea"]),
      e("🧃", ["juice box"]),
      e("🥤", ["cup straw", "soda"]),
      e("🧋", ["bubble tea", "boba"]),
      e("🍶", ["sake"]),
      e("🍺", ["beer"]),
      e("🍻", ["cheers"]),
      e("🥂", ["champagne"]),
      e("🍷", ["wine"]),
      e("🍕", ["pizza"]),
      e("🍔", ["burger"]),
      e("🍟", ["fries"]),
      e("🌭", ["hot dog"]),
      e("🥪", ["sandwich"]),
      e("🌮", ["taco"]),
      e("🌯", ["burrito"]),
      e("🥗", ["salad", "healthy"]),
      e("🍝", ["pasta", "spaghetti"]),
      e("🍜", ["noodles", "ramen"]),
      e("🍣", ["sushi"]),
      e("🍱", ["bento"]),
      e("🥡", ["takeout"]),
      e("🍩", ["donut"]),
      e("🍪", ["cookie"]),
      e("🎂", ["cake", "birthday"]),
      e("🍰", ["shortcake"]),
      e("🧁", ["cupcake"]),
      e("🍫", ["chocolate"]),
      e("🍬", ["candy"]),
      e("🍎", ["apple", "red"]),
      e("🍊", ["orange"]),
      e("🍋", ["lemon"]),
      e("🍌", ["banana"]),
      e("🍉", ["watermelon"]),
      e("🍇", ["grapes"]),
      e("🍓", ["strawberry"]),
      e("🥑", ["avocado"]),
      e("🌶️", ["pepper", "spicy"]),
      e("🧄", ["garlic"]),
      e("🧅", ["onion"]),
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "✈️",
    emojis: [
      e("✈️", ["airplane", "flight", "travel"]),
      e("🛫", ["departure"]),
      e("🛬", ["arrival"]),
      e("🚀", ["rocket", "space"]),
      e("🛸", ["ufo"]),
      e("🚁", ["helicopter"]),
      e("🚂", ["train"]),
      e("🚆", ["metro"]),
      e("🚇", ["subway"]),
      e("🚈", ["light rail"]),
      e("🚊", ["tram"]),
      e("🚉", ["station"]),
      e("🚌", ["bus"]),
      e("🚎", ["trolleybus"]),
      e("🏎️", ["race car", "fast"]),
      e("🚗", ["car", "auto"]),
      e("🚕", ["taxi"]),
      e("🚙", ["suv"]),
      e("🛻", ["pickup"]),
      e("🚚", ["truck", "delivery"]),
      e("🚲", ["bike", "bicycle"]),
      e("🛴", ["scooter"]),
      e("🛵", ["motor scooter"]),
      e("🏍️", ["motorcycle"]),
      e("🛳️", ["ship", "cruise"]),
      e("⛵", ["sailboat"]),
      e("🚤", ["speedboat"]),
      e("⚓", ["anchor"]),
      e("🗺️", ["map", "world"]),
      e("🗾", ["japan map"]),
      e("🏝️", ["island", "vacation"]),
      e("🏖️", ["beach"]),
      e("🏜️", ["desert"]),
      e("🏔️", ["mountain"]),
      e("⛺", ["tent", "camp"]),
      e("🏠", ["house", "home"]),
      e("🏡", ["house garden"]),
      e("🏢", ["office"]),
      e("🏨", ["hotel"]),
      e("🗽", ["statue liberty", "nyc"]),
      e("🗼", ["tokyo tower"]),
      e("🌍", ["world", "global"]),
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "✅",
    emojis: [
      e("✅", ["check", "yes", "done"]),
      e("❌", ["no", "cross", "wrong"]),
      e("⭕", ["circle"]),
      e("❎", ["cross mark button"]),
      e("✔️", ["check mark"]),
      e("☑️", ["checkbox"]),
      e("➕", ["plus", "add"]),
      e("➖", ["minus"]),
      e("✖️", ["multiply"]),
      e("➗", ["divide"]),
      e("♾️", ["infinity"]),
      e("‼️", ["bang bang"]),
      e("⁉️", ["interrobang"]),
      e("❓", ["question"]),
      e("❔", ["white question"]),
      e("❕", ["white exclamation"]),
      e("❗", ["exclamation"]),
      e("〰️", ["wavy dash"]),
      e("💱", ["exchange"]),
      e("💲", ["dollar"]),
      e("⚕️", ["medical"]),
      e("♻️", ["recycle"]),
      e("⚛️", ["atom"]),
      e("🔱", ["trident"]),
      e("📛", ["name badge"]),
      e("🔰", ["beginner", "new"]),
      e("⭕", ["hollow red circle"]),
      e("🅰️", ["a button"]),
      e("🆗", ["ok", "okay"]),
      e("🆕", ["new"]),
      e("🆓", ["free"]),
      e("🔴", ["red circle"]),
      e("🟠", ["orange circle"]),
      e("🟡", ["yellow circle"]),
      e("🟢", ["green circle"]),
      e("🔵", ["blue circle"]),
      e("🟣", ["purple circle"]),
      e("⚫", ["black circle"]),
      e("⚪", ["white circle"]),
      e("🟤", ["brown circle"]),
      e("▶️", ["play"]),
      e("⏸️", ["pause"]),
      e("⏹️", ["stop"]),
      e("⏺️", ["record"]),
      e("⏭️", ["next"]),
      e("⏮️", ["previous"]),
      e("➡️", ["arrow right"]),
      e("⬅️", ["arrow left"]),
      e("⬆️", ["arrow up"]),
      e("⬇️", ["arrow down"]),
      e("↗️", ["arrow up right"]),
      e("↘️", ["arrow down right"]),
      e("↩️", ["return"]),
      e("🔄", ["refresh", "reload"]),
      e("🔀", ["shuffle"]),
      e("🔁", ["repeat"]),
      e("🔃", ["arrows clockwise"]),
      e("→", ["arrow", "right"]),
      e("←", ["arrow left"]),
      e("↑", ["up"]),
      e("↓", ["down"]),
      e("•", ["bullet", "dot"]),
      e("◦", ["white bullet"]),
      e("▪️", ["small square"]),
      e("▫️", ["white square"]),
      e("—", ["dash", "em dash"]),
      e("–", ["en dash"]),
      e("…", ["ellipsis"]),
      e("「", ["bracket"]),
      e("」", ["bracket"]),
      e("【", ["bracket"]),
      e("】", ["bracket"]),
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏳️",
    emojis: [
      e("🏳️", ["white flag"]),
      e("🏴", ["black flag"]),
      e("🏁", ["checkered", "finish"]),
      e("🚩", ["triangular flag", "red flag"]),
      e("🎌", ["crossed flags"]),
      e("🏳️‍🌈", ["rainbow", "pride"]),
      e("🇺🇸", ["usa", "america", "united states"]),
      e("🇬🇧", ["uk", "britain", "united kingdom"]),
      e("🇨🇦", ["canada"]),
      e("🇦🇺", ["australia"]),
      e("🇩🇪", ["germany"]),
      e("🇫🇷", ["france"]),
      e("🇮🇳", ["india"]),
      e("🇯🇵", ["japan"]),
      e("🇨🇳", ["china"]),
      e("🇧🇷", ["brazil"]),
      e("🇲🇽", ["mexico"]),
      e("🇪🇸", ["spain"]),
      e("🇮🇹", ["italy"]),
      e("🇳🇱", ["netherlands"]),
      e("🇸🇪", ["sweden"]),
      e("🇨🇭", ["switzerland"]),
      e("🇰🇷", ["korea", "south korea"]),
      e("🇸🇬", ["singapore"]),
      e("🇦🇪", ["uae", "dubai"]),
      e("🇮🇱", ["israel"]),
      e("🇿🇦", ["south africa"]),
      e("🇳🇬", ["nigeria"]),
      e("🇵🇰", ["pakistan"]),
      e("🇵🇭", ["philippines"]),
      e("🇮🇩", ["indonesia"]),
      e("🇳🇿", ["new zealand"]),
      e("🇮🇪", ["ireland"]),
      e("🇵🇱", ["poland"]),
      e("🇺🇦", ["ukraine"]),
      e("🇷🇺", ["russia"]),
      e("🇹🇷", ["turkey"]),
      e("🇸🇦", ["saudi arabia"]),
      e("🇦🇷", ["argentina"]),
      e("🇨🇴", ["colombia"]),
    ],
  },
];

const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((category) => category.emojis);

const UNIQUE_EMOJIS = Array.from(new Map(ALL_EMOJIS.map((entry) => [entry.emoji, entry])).values());

export function searchEmojis(query: string): EmojiEntry[] {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return [];
  }

  return UNIQUE_EMOJIS.filter((entry) => {
    if (entry.emoji.includes(normalized)) {
      return true;
    }

    return entry.keywords.some(
      (keyword) => keyword.includes(normalized) || normalized.includes(keyword),
    );
  });
}

export function getCategoryById(id: string) {
  return EMOJI_CATEGORIES.find((category) => category.id === id);
}
