// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import openNextWorker, {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "../.open-next/worker.js";
import {
  chunkResponseHeaders,
  isAllowedChunkRequest,
  isProtectedChunkPath,
} from "../src/lib/chunk-access-guard.js";
import { getInternalRouteDenyReason } from "../src/lib/route-access-policy.js";

export { BucketCachePurge, DOQueueHandler, DOShardedTagCache };

type FetchHandler = {
  fetch: (request: Request, env: unknown, ctx: ExecutionContext) => Promise<Response>;
};

const openNext = openNextWorker as FetchHandler;

function respondToCdnCgiRum(request: Request): Response {
  if (request.method === "GET" || request.method === "HEAD") {
    return Response.redirect(new URL("/", request.url), 302);
  }

  if (request.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: {
        Allow: "GET, HEAD, POST, OPTIONS",
      },
    });
  }

  return new Response(null, { status: 204 });
}

function denyInternalRoute(request: Request, reason: "redirect" | "forbidden"): Response {
  if (reason === "redirect") {
    return Response.redirect(new URL("/", request.url), 302);
  }

  return new Response(null, {
    status: 403,
    headers: {
      "Cache-Control": "no-store",
    },
  });
}

function denyChunkRequest(): Response {
  return new Response(null, {
    status: 403,
    headers: {
      "Cache-Control": "no-store",
    },
  });
}

function withChunkVary(response: Response): Response {
  const headers = new Headers(response.headers);
  headers.set("Vary", chunkResponseHeaders.vary);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

const entryWorker = {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const { pathname } = new URL(request.url);

    if (pathname === "/cdn-cgi/rum") {
      return respondToCdnCgiRum(request);
    }

    const denyReason = getInternalRouteDenyReason(pathname, request);

    if (denyReason) {
      return denyInternalRoute(request, denyReason);
    }

    if (isProtectedChunkPath(pathname) && !isAllowedChunkRequest(request)) {
      return denyChunkRequest();
    }

    const response = await openNext.fetch(request, env, ctx);

    if (isProtectedChunkPath(pathname) && response.ok) {
      return withChunkVary(response);
    }

    return response;
  },
};

export default entryWorker;
