// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import openNextWorker, {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "../.open-next/worker.js";

export { BucketCachePurge, DOQueueHandler, DOShardedTagCache };

type FetchHandler = {
  fetch: (
    request: Request,
    env: unknown,
    ctx: ExecutionContext,
  ) => Promise<Response>;
};

const openNext = openNextWorker as FetchHandler;

/**
 * Cloudflare Web Analytics posts to `/cdn-cgi/rum`. When RUM is not enabled for the
 * zone, Cloudflare can surface a 404. Handle it in the worker instead.
 */
function respondToCdnCgiRum(request: Request): Response {
  if (request.method === "GET" || request.method === "HEAD") {
    return Response.redirect(new URL("/", request.url), 302);
  }

  if (request.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: {
        Allow: "GET, HEAD, POST, OPTIONS",
      },
    });
  }

  return new Response(null, { status: 204 });
}

export default {
  async fetch(
    request: Request,
    env: unknown,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const { pathname } = new URL(request.url);

    if (pathname === "/cdn-cgi/rum") {
      return respondToCdnCgiRum(request);
    }

    return openNext.fetch(request, env, ctx);
  },
};
